@startuml MemorySystem
interface PhasedSystemTrait {
    void init(...)
    void post_init(...)
    void runtime_init(...)
}

package "Kernel Memory Allocator" {
    interface KMallocTrait {
        void kmalloc_pre_init(void)
        void kmalloc_post_init(void)
        ==
        void *kmalloc(size_t size)
        void kfree(void *ptr)
    }
    class Stage1Allocator {
        void stage1_allocator_init(void)
        ==
        void *stage1_kmalloc(size_t size)
        void stage1_kfree(void *ptr)
    }

    class Stage2Allocator {
        void stage2_allocator_post_init(void)
        ==
        void *stage2_kmalloc(size_t size)
        void stage2_kfree(void *ptr)
    }
}

package "Task Memory" {
    struct AdditionalFrameInfo {
        qword flags
        int ref_count
    }
    struct PMA {
        void *paddr;
        size_t size;
        ===
        PMA *prev;
        PMA *next;
    }
    interface RPMA {
        void rpma_init(void)
        ===
        PMA *rpma_alloc_frames(size_t count)
        void rpma_free_frames(PMA *pma)
        void rpma_ref_frames(PMA *pma, qword flags)
        void rpma_deref_frame(void *paddr, size_t size)
        ===
        AdditionalFrameInfo *rpma_get_additional_info(void *paddr)
    }
    enum VMAType {
        VMAT_NONE      = 0
        VMAT_CODE      = 1
        VMAT_DATA      = 2
        VMAT_STACK     = 3
        VMAT_HEAP      = 4
        VMAT_MMAP      = 5
        VMAT_SHARE_RW  = 6
        VMAT_SHARE_RO  = 7
        VMAT_SHARE_RX  = 8
        VMAT_SHARE_RWX = 9
    }
    struct VMA {
        struct VMA *prev
        struct VMA *next
        ===
        void *vaddr
        size_t size
        VMAType type
    }
    struct TM {
        VMA *vma_list_head
        VMA *vma_list_tail
        void *pgd
        ===
        TM  *setup_task_memory(void)
        void tm_add_vma(TM *tm, VMA *vma)
        void tm_clone_vma(TM *dst_tm, TM *src_tm, VMA *vma)
        void tm_remove_vma(TM *tm, VMA *vma)
        VMA *tm_find_vma(TM *tm, void *vaddr)
        int  from_seg_to_rwx(VMAType seg_type)
    }
}

package "Page Frame Allocator" {
    interface PFATrait {
        void pfa_pre_init(size_t total_frames)
        void pfa_post_init(void)
        ==
        void *pfa_alloc_frame(void)
        void *pfa_alloc_frames(size_t count)
        void pfa_free_frame(void *frame)
        void pfa_free_frames(void *frame, size_t count)
    }
    class Buddy {
        void buddy_pre_init(size_t total_frames)
        void buddy_post_init(void)
        ==
        void *buddy_alloc_frame(void)
        void *buddy_alloc_frames(size_t count)
        void *buddy_alloc_frame_in_order(int order)
        void buddy_free_frame(void *frame)
        void buddy_free_frames(void *frame, size_t count)
        void buddy_free_frame_in_order(void *frame, int order)
        ==
        int pages2order(size_t pages)
    }
}

package "Kernel Object Allocator" {
    interface KOATrait {
        KOCache *koa_create_cache(const char *name, size_t ko_size, size_t align, qword flags)
        void koa_destroy_cache(KOCache *cache)
        void *koa_alloc(KOCache *cache, qword flags)
        void koa_free(KOCache *cache, void *ko)
    }
    class TrivalKOA {
        void TrivalKOCache *tkoa_create_cache(const char *name, size_t ko_size, size_t align, qword flags)
        void tkoa_destroy_cache(TrivalKOCache *cache)
        void tkoa_alloc(TrivalKOCache *cache, qword flags)
        void tkoa_free(TrivalKOCache *cache, void *ko)
    }
    class SlubKOA {
        SlubKOCache *skoa_create_cache(const char *name, size_t ko_size, size_t align, qword flags)
        void skoa_destroy_cache(SlubKOA *cache)
        void skoa_alloc(SlubKOA *cache, qword flags)
        void skoa_free(SlubKOA *cache, void *ko)
    }
}

PhasedSystemTrait <|..|> PFATrait
PhasedSystemTrait <|..|> KMallocTrait
PFATrait --> KMallocTrait
KOATrait --> PFATrait
KOATrait --> KMallocTrait
PFATrait <|.. Buddy
KMallocTrait <|.. Stage1Allocator
KMallocTrait <|.. Stage2Allocator
Stage2Allocator -> Stage1Allocator
Stage2Allocator --> PFATrait
TrivalKOA ..|> KOATrait
TrivalKOA --> KMallocTrait
SlubKOA ..|> KOATrait
VMA *-- VMAType
TM *-- VMA
TM --> RPMA
RPMA *-- AdditionalFrameInfo
RPMA *-- PMA
RPMA --> PFATrait
@enduml