[[dependencies]]
lib = "gcc-cheaders"
version = "*.*.*"

[[dependencies]]
lib = "mini-cstd"
version = "*.*.*"

[[dependencies]]
lib = "mini-cppstd"
version = "*.*.*"

[[dependencies]]
lib = "kmod"
version = "*.*.*"
