#!/usr/bin/env python3
"""Persist the selected build architecture and mode."""

import sys
from pathlib import Path

from common.arguments import parse_key_value_arguments
from common.constants import ARCHITECTURES, BUILD_MODES
from common.filesystem import atomic_write_text
from common.paths import CACHE_ROOT


SUPPORTED_ARCHITECTURES = set(ARCHITECTURES)
SUPPORTED_MODES = set(BUILD_MODES)


def parse_arguments(arguments):
    values = parse_key_value_arguments(
        arguments,
        {"arch", "mode"},
        required_keys={"arch", "mode"},
        non_empty_keys={"arch", "mode"},
    )

    if values["arch"] not in SUPPORTED_ARCHITECTURES:
        raise ValueError(f"unsupported architecture: {values['arch']}")
    if values["mode"] not in SUPPORTED_MODES:
        raise ValueError(f"unsupported mode: {values['mode']}")
    return values


def write_switch_file(path, values):
    content = (
        "# Generated by script/py/switch.py. Do not edit this file directly.\n"
        f"cached-arch := {values['arch']}\n"
        f"cached-mode := {values['mode']}\n"
    )

    atomic_write_text(path, content)


def main(arguments):
    try:
        values = parse_arguments(arguments)
        cache_path = CACHE_ROOT / ".switch.mk"
        write_switch_file(cache_path, values)
    except (OSError, ValueError) as error:
        print(f"switch.py: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
