#!/usr/bin/env python3
import json
import re
import sys
from pathlib import Path


MACRO_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def default_config_path():
    local_config = Path("config.json")
    if local_config.exists():
        return local_config
    return Path("script/config.default.json")


def require_object(value, name):
    if not isinstance(value, dict):
        raise ValueError(f"{name} must be an object")
    return value


def optional_list(value, name):
    if value is None:
        return []
    if not isinstance(value, list):
        raise ValueError(f"{name} must be an array")
    return value


def require_macro(value, name):
    if not isinstance(value, str) or not MACRO_RE.fullmatch(value):
        raise ValueError(f"{name} must be a valid C/C++ macro name")
    return value


def require_string(value, name):
    if not isinstance(value, str) or not value:
        raise ValueError(f"{name} must be a non-empty string")
    return value


def resolve_arch_config(config, override_arch=None):
    config = require_object(config, "config")
    arch = override_arch or require_string(config.get("arch"), "arch")
    arch_config = require_object(config.get(arch), arch)
    return arch, arch_config


def emit_feature_makefile(feature_config, config, override_arch=None):
    feature_config = require_object(feature_config, "feature config")
    arch, arch_config = resolve_arch_config(config, override_arch)
    features = optional_list(arch_config.get("features"), f"{arch}.features")

    for feature in features:
        if not isinstance(feature, str):
            raise ValueError("features entries must be strings")

    unknown_features = sorted(set(features) - set(feature_config))
    if unknown_features:
        raise ValueError(
            "unknown feature(s): " + ", ".join(str(item) for item in unknown_features)
        )

    defs = []
    for feature in features:
        entry = require_object(feature_config[feature], f"feature.{feature}")
        macro = require_macro(entry.get("macro"), f"feature.{feature}.macro")
        defs.append(f"-D{macro}=1")

    lines = [
        "# Generated by tools/feature_gen/feature_gen.py.",
        "# Do not edit this file directly.",
        "",
    ]

    if defs:
        lines.append("kernel-feature-defs := " + " ".join(defs))
    else:
        lines.append("kernel-feature-defs :=")

    lines.append("")
    return "\n".join(lines)


def write_text_if_changed(path, content):
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def main(argv):
    if len(argv) > 5:
        print(
            "usage: feature_gen.py [kernel/feature.json] [kernel/feature.mk] "
            "[config.json] [arch]",
            file=sys.stderr,
        )
        return 2

    feature_input_path = (
        Path(argv[1]) if len(argv) >= 2 else Path("kernel/feature.json")
    )
    output_path = Path(argv[2]) if len(argv) >= 3 else Path("kernel/feature.mk")
    config_path = Path(argv[3]) if len(argv) >= 4 else default_config_path()
    override_arch = argv[4] if len(argv) >= 5 else None

    try:
        with feature_input_path.open(encoding="utf-8") as fp:
            feature_config = json.load(fp)
        with config_path.open(encoding="utf-8") as fp:
            config = json.load(fp)
        write_text_if_changed(
            output_path, emit_feature_makefile(feature_config, config, override_arch)
        )
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"feature_gen.py: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
