namespace ltp {
    const char *testcase01_uname_personality[] = {
        "uname01",
        // "uname02",
        "uname04",
        "newuname01",
        // "personality01",
        nullptr,
    };

    const char *testcase02_random[] = {
        "getrandom01",
        "getrandom02",
        "getrandom03",
        "getrandom04",
        "getrandom05",
        nullptr,
    };

    const char *testcase03_time[] = {
        // "gettimeofday01",
        // "gettimeofday02",
        // "clock_gettime01",
        // "clock_gettime02",
        // "clock_gettime03",
        // "clock_gettime04",
        "times01",
        // "times03",
        nullptr,
    };

    const char *testcase04_process_basic[] = {
        "sched_yield01",
        // "getpid01",
        "getpid02",
        // "getppid01",
        "getppid02",
        // "gettid01",
        // "gettid02",
        // "brk01",
        "brk02",
        "sbrk01",
        "sbrk02",
        // "sbrk03",
        nullptr,
    };

    const char *testcase05_close_dup[] = {
        "close01",
        "close02",
        "dup01",
        "dup02",
        // "dup03",
        "dup04",
        // "dup05",
        // "dup06",
        "dup07",
        "dup201",
        "dup202",
        "dup203",
        "dup204",
        // "dup205",
        "dup206",
        "dup207",
        "dup3_01",
        "dup3_02",
        // "close_range01",
        // "close_range02",
        nullptr,
    };

    const char *testcase06_read_write[] = {
        "read01",
        // "read02",
        // "read03",
        "read04",
        // "write01",
        "write02",
        // "write03",
        // "write04",
        "write05",
        // "write06",
        nullptr,
    };

    const char *testcase07_readv_writev[] = {
        "readv01",
        "readv02",
        // "writev01",
        // "writev02",
        // "writev03",
        // "writev05",
        "writev06",
        // "writev07",
        nullptr,
    };

    const char *testcase08_pread_pwrite[] = {
        "pread01",
        "pread01_64",
        "pread02",
        "pread02_64",
        "pwrite01",
        "pwrite01_64",
        "pwrite02",
        "pwrite02_64",
        "pwrite03",
        "pwrite03_64",
        "pwrite04",
        "pwrite04_64",
        nullptr,
    };

    const char *testcase09_preadv_pwritev[] = {
        "preadv01",
        "preadv01_64",
        "preadv02",
        "preadv02_64",
        "preadv03",
        "preadv03_64",
        "preadv201",
        "preadv201_64",
        "preadv202",
        "preadv202_64",
        "preadv203",
        "preadv203_64",
        "pwritev01",
        "pwritev01_64",
        "pwritev02",
        "pwritev02_64",
        "pwritev03",
        "pwritev03_64",
        "pwritev201",
        "pwritev201_64",
        "pwritev202",
        "pwritev202_64",
        nullptr,
    };

    const char *testcase10_copy_sendfile_readahead[] = {
        "copy_file_range01",
        "copy_file_range02",
        "copy_file_range03",
        "sendfile02",
        "sendfile02_64",
        "sendfile03",
        "sendfile03_64",
        "sendfile04",
        "sendfile04_64",
        "sendfile05",
        "sendfile05_64",
        "sendfile06",
        "sendfile06_64",
        "sendfile07",
        "sendfile07_64",
        "sendfile08",
        "sendfile08_64",
        "sendfile09",
        "sendfile09_64",
        "readahead01",
        "readahead02",
        nullptr,
    };

    const char *testcase11_lseek[] = {
        "lseek01",
        // "lseek02",
        "lseek07",
        // "lseek11",
        nullptr,
    };

    const char *testcase12_cwd_chdir[] = {
        "getcwd01",
        "getcwd02",
        "getcwd03",
        "getcwd04",
        "chdir01",
        "chdir04",
        nullptr,
    };

    const char *testcase13_getdents_readlink[] = {
        // "getdents01",
        // "getdents02",
        // "readlink01",
        // "readlink03",
        "readlinkat01",
        "readlinkat02",
        nullptr,
    };

    const char *testcase14_mkdir_unlink[] = {
        // "mkdir02",
        // "mkdir03",
        // "mkdir04",
        // "mkdir05",
        // "mkdir09",
        "mkdirat01",
        // "mkdirat02",
        "unlink05",
        "unlink07",
        // "unlink08",
        // "unlink09",
        // "unlinkat01",
        nullptr,
    };

    const char *testcase15_rename[] = {
        "rename01",
        "rename03",
        "rename04",
        "rename05",
        "rename06",
        "rename07",
        "rename08",
        "rename09",
        "rename10",
        "rename11",
        "rename12",
        "rename13",
        "rename14",
        "renameat01",
        "renameat201",
        "renameat202",
        nullptr,
    };

    const char *testcase16_open_creat[] = {
        "open01",
        // "open02",
        "open03",
        // "open04",
        // "open06",
        "open07",
        // "open08",
        // "open09",
        // "open10",
        // "open11",
        // "open12",
        // "open13",
        // "open14",
        // "creat01",
        // "creat03",
        // "creat04",
        // "creat05",
        // "creat06",
        // "creat07",
        // "creat08",
        // "creat09",
        // "faccessat01",
        // "faccessat02",
        // "faccessat201",
        // "faccessat202",
        nullptr,
    };

    const char *testcase17_openat[] = {
        "openat01",
        "openat02",
        "openat03",
        "openat04",
        "openat201",
        "openat202",
        "openat203",
        nullptr,
    };

    const char *testcase18_stat_core[] = {
        // "fstat02",
        "fstat03",
        // "stat01",
        "stat02",
        // "stat03",
        "lstat01",
        // "lstat02",
        "fstatat01",
        // "statx01",
        "statx02",
        // "statx03",
        nullptr,
    };

    const char *testcase19_statx_extended[] = {
        "statx04",
        "statx05",
        "statx06",
        "statx07",
        "statx08",
        "statx09",
        "statx10",
        "statx11",
        "statx12",
        nullptr,
    };

    const char *testcase20_chmod_chown_at[] = {
        "fchmodat01",
        // "fchmodat02",
        "fchownat01",
        // "fchownat02",
        "chmod01",
        // "chmod03",
        // "chmod05",
        // "chmod06",
        // "chmod07",
        nullptr,
    };

    const char *testcase21_chown_variants[] = {
        "chown01",
        "chown02",
        // "chown03",
        // "chown04",
        "chown05",
        // "fchown01",
        // "fchown02",
        // "fchown03",
        // "fchown04",
        // "fchown05",
        // "lchown01",
        // "lchown02",
        // "lchown03",
        nullptr,
    };

    const char *testcase22_statfs_statvfs[] = {
        "fstatfs01",
        "fstatfs01_64",
        "fstatfs02",
        "fstatfs02_64",
        "statfs01",
        "statfs01_64",
        "statfs02",
        "statfs02_64",
        "statfs03",
        "statfs03_64",
        "statvfs01",
        "statvfs02",
        nullptr,
    };

    const char *testcase23_truncate[] = {
        "ftruncate01",
        // "ftruncate03",
        // "ftruncate04",
        "ftruncate01_64",
        // "ftruncate03_64",
        // "ftruncate04_64",
        // "truncate02",
        // "truncate03",
        // "truncate02_64",
        // "truncate03_64",
        nullptr,
    };

    const char *testcase24_sync[] = {
        "fsync01",
        "fsync02",
        "fsync03",
        "fsync04",
        "fdatasync01",
        "fdatasync02",
        "fdatasync03",
        "sync01",
        "syncfs01",
        "sync_file_range01",
        "sync_file_range02",
        nullptr,
    };

    const char *testcase25_mmap_basic[] = {
        // "mmap01",
        // "mmap02",
        // "mmap03",
        // "mmap04",
        // "mmap05",
        // "mmap06",
        // "mmap08",
        "mmap09",
        // "mmap10",
        // "mmap11",
        // "mmap12",
        // "mmap13",
        // "munmap01",
        // "munmap02",
        // "munmap03",
        nullptr,
    };

    const char *testcase26_mmap_extended[] = {
        "mmap14",
        "mmap15",
        "mmap16",
        "mmap17",
        "mmap18",
        "mmap19",
        "mmap20",
        "mmap001",
        "mmap1",
        "mmap2",
        "mmap3",
        "mmap-corruption01",
        nullptr,
    };

    const char *testcase27_mmapstress[] = {
        "mmapstress01",
        "mmapstress02",
        "mmapstress03",
        "mmapstress04",
        "mmapstress05",
        "mmapstress06",
        "mmapstress07",
        "mmapstress08",
        "mmapstress09",
        "mmapstress10",
        nullptr,
    };

    const char *testcase28_mprotect_msync[] = {
        "mprotect01",
        "mprotect02",
        "mprotect03",
        "mprotect04",
        "mprotect05",
        "msync01",
        "msync02",
        "msync03",
        "msync04",
        nullptr,
    };

    const char *testcase29_mremap_madvise_mincore[] = {
        "mremap01",
        "mremap02",
        "mremap03",
        "mremap04",
        "mremap05",
        "mremap06",
        "madvise01",
        "madvise02",
        "madvise03",
        "madvise05",
        "madvise06",
        "madvise07",
        "madvise08",
        "madvise09",
        "madvise10",
        "madvise11",
        "mincore01",
        "mincore02",
        "mincore03",
        "mincore04",
        nullptr,
    };

    const char *testcase30_pipe[] = {
        "pipe01",
        // "pipe02",
        "pipe03",
        // "pipe04",
        "pipe05",
        // "pipe06",
        // "pipe07",
        // "pipe08",
        // "pipe09",
        "pipe10",
        "pipe11",
        // "pipe12",
        // "pipe13",
        "pipe14",
        // "pipe15",
        "pipe2_01",
        // "pipe2_02",
        // "pipe2_04",
        nullptr,
    };

    const char *testcase31_fcntl_a[] = {
        "fcntl01",
        "fcntl01_64",
        "fcntl02",
        "fcntl02_64",
        "fcntl03",
        "fcntl03_64",
        "fcntl04",
        "fcntl04_64",
        "fcntl05",
        "fcntl05_64",
        "fcntl07",
        "fcntl07_64",
        "fcntl08",
        "fcntl08_64",
        "fcntl09",
        "fcntl09_64",
        "fcntl10",
        "fcntl10_64",
        nullptr,
    };

    const char *testcase32_fcntl_b[] = {
        "fcntl11",
        "fcntl11_64",
        "fcntl12",
        "fcntl12_64",
        "fcntl13",
        "fcntl13_64",
        "fcntl14",
        "fcntl14_64",
        "fcntl15",
        "fcntl15_64",
        "fcntl16",
        "fcntl16_64",
        "fcntl17",
        "fcntl17_64",
        "fcntl18",
        "fcntl18_64",
        "fcntl19",
        "fcntl19_64",
        nullptr,
    };

    const char *testcase33_fcntl_c[] = {
        "fcntl20",
        "fcntl20_64",
        "fcntl21",
        "fcntl21_64",
        "fcntl22",
        "fcntl22_64",
        "fcntl23",
        "fcntl23_64",
        "fcntl24",
        "fcntl24_64",
        "fcntl25",
        "fcntl25_64",
        "fcntl26",
        "fcntl26_64",
        "fcntl27",
        "fcntl27_64",
        nullptr,
    };

    const char *testcase34_fcntl_d[] = {
        "fcntl29",
        "fcntl29_64",
        "fcntl30",
        "fcntl30_64",
        "fcntl31",
        "fcntl31_64",
        "fcntl32",
        "fcntl32_64",
        "fcntl33",
        "fcntl33_64",
        "fcntl34",
        "fcntl34_64",
        "fcntl35",
        "fcntl35_64",
        "fcntl36",
        "fcntl36_64",
        "fcntl37",
        "fcntl37_64",
        "fcntl38",
        "fcntl38_64",
        "fcntl39",
        "fcntl39_64",
        nullptr,
    };

    const char *testcase35_flock_ioctl[] = {
        "flock01",
        "flock02",
        "flock03",
        "flock04",
        "flock06",
        "ioctl01",
        "ioctl02",
        "ioctl03",
        "ioctl04",
        "ioctl05",
        "ioctl06",
        "ioctl07",
        "ioctl08",
        "ioctl09",
        nullptr,
    };

    const char *testcase36_wait_waitpid[] = {
        "wait01",
        "wait02",
        "wait401",
        "wait402",
        "wait403",
        "waitpid01",
        "waitpid03",
        "waitpid04",
        "waitpid06",
        "waitpid07",
        "waitpid08",
        "waitpid09",
        "waitpid10",
        "waitpid11",
        "waitpid12",
        "waitpid13",
        nullptr,
    };

    const char *testcase37_fork_clone[] = {
        "fork01",
        "fork03",
        "fork04",
        "fork05",
        "fork07",
        "fork08",
        "fork09",
        "fork10",
        "fork13",
        "fork14",
        "clone01",
        "clone02",
        "clone03",
        "clone04",
        "clone05",
        "clone06",
        "clone07",
        "clone08",
        "clone09",
        nullptr,
    };

    const char *testcase38_exec[] = {
        "execve01",
        "execve02",
        "execve03",
        "execve04",
        "execve05",
        "execve06",
        "execv01",
        "execvp01",
        "execl01",
        "execle01",
        "execlp01",
        nullptr,
    };

    const char *testcase39_misc_proc[] = {
        "set_tid_address01",
        "sched_getaffinity01",
        "getcpu01",
        nullptr,
    };

    const char *testcase40_memfd_fallocate[] = {
        "memfd_create01",
        "memfd_create02",
        "memfd_create03",
        "memfd_create04",
        "fallocate01",
        "fallocate02",
        "fallocate03",
        "fallocate04",
        "fallocate05",
        "fallocate06",
        nullptr,
    };

    const char *testcase41_utime[] = {
        "utime01",
        "utime02",
        "utime03",
        "utime04",
        "utime05",
        "utime06",
        "utime07",
        "utimensat01",
        "utimes01",
        "futimesat01",
        nullptr,
    };

    const char **testcases[] = {
        // testcase01_uname_personality,
        // testcase02_random,
        // testcase03_time,
        // testcase04_process_basic,
        // testcase05_close_dup,
        // testcase06_read_write,
        // testcase07_readv_writev,
        // // testcase08_pread_pwrite,
        // // testcase09_preadv_pwritev,
        // // testcase10_copy_sendfile_readahead,
        // testcase11_lseek,
        // // testcase12_cwd_chdir,
        // testcase13_getdents_readlink,
        // testcase14_mkdir_unlink,
        // testcase15_rename,
        // testcase16_open_creat,
        // // testcase17_openat,
        // testcase18_stat_core,
        // // testcase19_statx_extended,
        // testcase20_chmod_chown_at,
        // testcase21_chown_variants,
        // // testcase22_statfs_statvfs,
        // testcase23_truncate,
        // // testcase24_sync,
        // testcase25_mmap_basic,
        // // testcase26_mmap_extended,
        // // testcase27_mmapstress,
        // // testcase28_mprotect_msync,
        // // testcase29_mremap_madvise_mincore,
        // testcase30_pipe,
        // testcase31_fcntl_a,
        // testcase32_fcntl_b,
        // testcase33_fcntl_c,
        // testcase34_fcntl_d,
        // testcase35_flock_ioctl,
        // testcase36_wait_waitpid,
        // testcase37_fork_clone,
        // testcase38_exec,
        // testcase39_misc_proc,
        testcase40_memfd_fallocate,
        // testcase41_utime,
        nullptr
    };
}  // namespace ltp
