[[dependencies]]
lib="gcc-cheaders"
version="*.*.*"

[[dependencies]]
lib="mini-cstd"
version="*.*.*"

[[dependencies]]
lib="mini-cppstd"
version="*.*.*"

[[dependencies]]
lib="tayclib"
version="*.*.*"

[[dependencies]]
lib="taycpplib"
version="*.*.*"

[[dependencies]]
lib="sustcore-headers"
version="*.*.*"

[[dependencies]]
lib="fdt"
version="*.*.*"

[[dependencies]]
lib="elf"
version="*.*.*"

[[dependencies]]
lib="linux-headers"
version="*.*.*"

[[dependencies]]
lib="multiboot"
version="*.*.*"

[[riscv64.dependencies]]
lib="sbi"
version="*.*.*"
