[[dependencies]]
lib = "gcc-cheaders"
version = ">=0.1.0-dev.0 <0.1.0"

[[dependencies]]
lib = "mini-cstd"
version = ">=0.1.0-dev.0 <0.1.0"

[[dependencies]]
lib = "mini-cppstd"
version = ">=0.1.0-dev.0 <0.1.0"

[[dependencies]]
lib = "tayclib"
version = ">=0.1.0-dev.0 <0.1.0"

[[dependencies]]
lib = "taycpplib"
version = ">=0.1.0-dev.0 <0.1.0"

[[dependencies]]
lib = "sustcore-headers"
version = ">=0.1.0-dev.0 <0.1.0"

[[dependencies]]
lib = "fdt"
version = ">=0.1.0-dev.0 <0.1.0"

[[dependencies]]
lib = "elf"
version = ">=0.1.0-dev.0 <0.1.0"

[[dependencies]]
lib = "linux-headers"
version = ">=0.1.0-dev.0 <0.1.0"

[[dependencies]]
lib = "multiboot"
version = ">=0.1.0-dev.0 <0.1.0"

[[riscv64.dependencies]]
lib = "sbi"
version = ">=0.1.0-dev.0 <0.1.0"
