#!/usr/bin/env python3
import json
import sys
from pathlib import Path


LOGGER_LEVELS = {
    "debug": "DEBUG",
    "info": "INFO",
    "warn": "WARN",
    "error": "ERROR",
    "fatal": "FATAL",
    "disable": "DISABLE",
}


def default_config_path():
    local_config = Path("config.json")
    if local_config.exists():
        return local_config
    return Path("script/config.default.json")


def require_object(value, name):
    if not isinstance(value, dict):
        raise ValueError(f"{name} must be an object")
    return value


def require_string(value, name):
    if not isinstance(value, str) or not value:
        raise ValueError(f"{name} must be a non-empty string")
    return value


def resolve_arch_config(config, override_arch=None):
    config = require_object(config, "config")
    arch = override_arch or require_string(config.get("arch"), "arch")
    arch_config = require_object(config.get(arch), arch)
    return arch, arch_config


def level_to_enum(level, name):
    level_key = str(level).lower()
    if level_key not in LOGGER_LEVELS:
        supported = ", ".join(LOGGER_LEVELS)
        raise ValueError(
            f"unsupported logger level {level!r} for {name}; "
            f"supported levels: {supported}"
        )
    return LOGGER_LEVELS[level_key]


def emit_logger_header(logger_config, config, override_arch=None):
    logger_config = require_object(logger_config, "logger config")
    _, arch_config = resolve_arch_config(config, override_arch)
    overrides = require_object(arch_config.get("logger", {}), "logger")
    disable_all = arch_config.get("logger-disable-all") is True

    unknown_loggers = sorted(set(overrides) - set(logger_config))
    if unknown_loggers:
        raise ValueError(
            "unknown logger override(s): " + ", ".join(unknown_loggers)
        )

    declarations = []
    for key, entry in logger_config.items():
        entry = require_object(entry, f"logger.{key}")
        require_string(entry.get("channel"), f"logger.{key}.channel")
        name = require_string(entry.get("name"), f"logger.{key}.name")
        default = entry.get("default")
        if default is None:
            raise ValueError(f"logger.{key}.default is required")

        if disable_all:
            level_enum = LOGGER_LEVELS["disable"]
        else:
            level = overrides.get(key, default)
            level_enum = level_to_enum(level, f"logger.{key}")

        declarations.append(
            f"    DECLARE_LOGGER(kputer, LogLevel::{level_enum}, {name});"
        )

    lines = [
        "/**",
        " * @file logger.h",
        " * @author auto-generated",
        " * @brief Generated logger declarations.",
        " *",
        " * Do not edit this file directly.",
        " */",
        "",
        "#pragma once",
        "",
        "#include <kio.h>",
        "#include <sus/logger.h>",
        "",
        "struct kputer {",
        "    int operator()(const char *str) const",
        "    {",
        "        return kputs(str);",
        "    }",
        "};",
        "",
        "namespace loggers {",
    ]
    lines.extend(declarations)
    lines.extend(["};  // namespace loggers", ""])
    return "\n".join(lines)


def write_text_if_changed(path, content):
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def main(argv):
    if len(argv) > 5:
        print(
            "usage: logger_gen.py [kernel/logger.json] [kernel/logger.h] "
            "[config.json] [arch]",
            file=sys.stderr,
        )
        return 2

    logger_input_path = (
        Path(argv[1]) if len(argv) >= 2 else Path("kernel/logger.json")
    )
    output_path = Path(argv[2]) if len(argv) >= 3 else Path("kernel/logger.h")
    config_path = Path(argv[3]) if len(argv) >= 4 else default_config_path()
    override_arch = argv[4] if len(argv) >= 5 else None

    try:
        with logger_input_path.open(encoding="utf-8") as fp:
            logger_config = json.load(fp)
        with config_path.open(encoding="utf-8") as fp:
            config = json.load(fp)
        write_text_if_changed(
            output_path, emit_logger_header(logger_config, config, override_arch)
        )
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"logger_gen.py: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
