/**
 * @file bootinfo.h
 * @author theflysong (song_of_the_fly@163.com)
 * @brief 启动信息
 * @version alpha-1.0.0
 * @date 2026-06-17
 * 
 * @copyright Copyright (c) 2026
 * 
 */

#pragma once

#define LABOOT_SETUP_ROOT_PAGE_TABLE_OFFSET 0
#define LABOOT_SETUP_PWCTL0_OFFSET 8
#define LABOOT_SETUP_PWCTL1_OFFSET 16
#define LABOOT_SETUP_STLBPGSIZE_OFFSET 24
#define LABOOT_SETUP_PGDL_OFFSET 32
#define LABOOT_SETUP_PGDH_OFFSET 40
#define LABOOT_SETUP_DMW0_OFFSET 48
#define LABOOT_SETUP_DMW1_OFFSET 56
#define LABOOT_SETUP_DMW2_OFFSET 64
#define LABOOT_SETUP_DMW3_OFFSET 72
#define LABOOT_SETUP_TLBRENTRY_OFFSET 80
#define LABOOT_SETUP_CRMD_VALUE_OFFSET 88
#define LABOOT_SETUP_POST_ENTRY_OFFSET 96
#define LABOOT_SETUP_BOOT_INFO_PTR_OFFSET 104
#define LABOOT_SETUP_RECLAIMABLE_CURSOR_OFFSET 112

#define LABOOT_BOOTINFO_BSP_OFFSET 0
#define LABOOT_BOOTINFO_DTB_PHYS_OFFSET 8
#define LABOOT_BOOTINFO_DTB_VIRT_OFFSET 16
#define LABOOT_BOOTINFO_HHDM_BASE_OFFSET 24
#define LABOOT_BOOTINFO_KERNEL_PHYS_BASE_OFFSET 32
#define LABOOT_BOOTINFO_KERNEL_VIRT_BASE_OFFSET 40
#define LABOOT_BOOTINFO_KERNEL_PHYS_END_OFFSET 48
#define LABOOT_BOOTINFO_KERNEL_VIRT_END_OFFSET 56
#define LABOOT_BOOTINFO_ROOT_PGTBL_PHYS_OFFSET 64
#define LABOOT_BOOTINFO_ROOT_PGTBL_VIRT_OFFSET 72
#define LABOOT_BOOTINFO_CMDLINE_PHYS_OFFSET 80
#define LABOOT_BOOTINFO_SYSTEM_TABLE_PHYS_OFFSET 88
#define LABOOT_BOOTINFO_CMDLINE_VIRT_OFFSET 96
#define LABOOT_BOOTINFO_SYSTEM_TABLE_VIRT_OFFSET 104