/**
 * @file macros.h
 * @author theflysong (song_of_the_fly@163.com)
 * @brief 页表相关宏
 * @version alpha-1.0.0
 * @date 2026-06-15
 *
 * @copyright Copyright (c) 2026
 *
 */

#pragma once

#define CSR_CRMD 0x0
#define CSR_PRMD 0x1
#define CSR_ECFG 0x4
#define CSR_ESTAT 0x5
#define CSR_ERA 0x6
#define CSR_BADV 0x7
#define CSR_EENTRY 0xc
#define CSR_PGDL 0x19
#define CSR_PGDH 0x1a
#define CSR_PGD 0x1b
#define CSR_PWCTL0 0x1c
#define CSR_PWCTL1 0x1d
#define CSR_STLBPGSIZE 0x1e
#define CSR_CPUID 0x20
#define CSR_TCFG 0x41
#define CSR_TVAL 0x42
#define CSR_TICLR 0x44
#define CSR_KS0 0x30
#define CSR_KS1 0x31
#define CSR_KS2 0x32
#define CSR_KS3 0x33
#define CSR_KS4 0x34
#define CSR_EUEN 0x2
#define CSR_TLBRENTRY 0x88
#define CSR_TLBRSAVE 0x8b
#define CSR_DMWIN0 0x180
#define CSR_DMWIN1 0x181
#define CSR_DMWIN2 0x182
#define CSR_DMWIN3 0x183

#define CRMD_PLV_MASK 0x3UL
#define CRMD_IE (1UL << 2)
#define CRMD_DA (1UL << 3)
#define CRMD_PG (1UL << 4)

#define PWCTL0_4LEVEL                                                \
    ((9UL << 25) | (30UL << 20) | (9UL << 15) | (21UL << 10) | (9UL << 5) |    \
     12UL)
#define PWCTL1_4LEVEL (39UL | (9UL << 6))
#define STLBPGSIZE_4K 12UL

#define DMW_PLV0 (1UL << 0)
#define DMW_MAT_CC (1UL << 4)
#define DMW0_BASE 0x8000000000000000ULL
#define DMW0_CONFIG                                                  \
    (DMW0_BASE | DMW_MAT_CC | DMW_PLV0)

#define LABOOT_PAGE_PRESENT  0x80
#define LABOOT_PAGE_GLOBAL   0x40
#define LABOOT_PAGE_CACHE_CC 0x10
#define LABOOT_PAGE_MODIFIED 0x200
#define LABOOT_PAGE_WRITE    0x100
#define LABOOT_PAGE_DIRTY    0x2
#define LABOOT_PAGE_VALID    0x1

#define LABOOT_PTE_FLAGS 0x3d3

#define LABOOT_PPN_MASK 0x0000FFFFFFFFF000ULL

#define EUEN_FPE (1UL << 0)
#define EUEN_SXE (1UL << 1)
#define EUEN_ASXE (1UL << 2)

#define ESTAT_IS_SHIFT 0
#define ESTAT_IS_MASK 0x1fffUL
#define ESTAT_ECODE_SHIFT 16
#define ESTAT_ECODE_MASK 0x3fUL
#define ECFG_VS_MASK (0x7UL << 16)

#define ECODE_INT 0
#define ECODE_SYS 0xb
#define ECODE_FPD 0xf
#define ECODE_SXD 0x10
#define ECODE_ASXD 0x11

#define INT_TIMER 11
#define ECFG_TIMER (1UL << INT_TIMER)

#define TCFG_EN (1UL << 0)
#define TCFG_PERIODIC (1UL << 1)
#define TCFG_INITVAL_SHIFT 2

#define TICLR_CLR (1UL << 0)

#define PRMD_PPLV_MASK 0x3UL
#define PRMD_PIE (1UL << 2)

#define PLV_KERNEL 0UL
#define PLV_USER 3UL
#define PRMD_USER (PLV_USER | PRMD_PIE)

#define ECODE_PIL 0x1
#define ECODE_PIS 0x2
#define ECODE_PIF 0x3
#define ECODE_PME 0x4
#define ECODE_PNR 0x5
#define ECODE_PNX 0x6
#define ECODE_PPI 0x7

#define IOCSR_IPI_STATUS 0x1000
#define IOCSR_IPI_EN 0x1004
#define IOCSR_IPI_SET 0x1008
#define IOCSR_IPI_CLEAR 0x100c
#define IOCSR_MBUF0 0x1020
#define IOCSR_MBUF1 0x1028
#define IOCSR_MBUF2 0x1030
#define IOCSR_MBUF3 0x1038
#define IOCSR_IPI_SEND 0x1040
#define IOCSR_MBUF_SEND 0x1048

#define IOCSR_IPI_SEND_IP_SHIFT 0
#define IOCSR_IPI_SEND_CPU_SHIFT 16
#define IOCSR_IPI_SEND_BLOCKING (1UL << 31)
#define IOCSR_MBUF_SEND_BLOCKING (1ULL << 31)
#define IOCSR_MBUF_SEND_BOX_SHIFT 2
#define IOCSR_MBUF_SEND_CPU_SHIFT 16

#define LABOOT_SETUP_ROOT_PAGE_TABLE_OFFSET 0
#define LABOOT_SETUP_PWCTL0_OFFSET 8
#define LABOOT_SETUP_PWCTL1_OFFSET 16
#define LABOOT_SETUP_STLBPGSIZE_OFFSET 24
#define LABOOT_SETUP_PGDL_OFFSET 32
#define LABOOT_SETUP_PGDH_OFFSET 40
#define LABOOT_SETUP_DMW0_OFFSET 48
#define LABOOT_SETUP_DMW1_OFFSET 56
#define LABOOT_SETUP_DMW2_OFFSET 64
#define LABOOT_SETUP_DMW3_OFFSET 72
#define LABOOT_SETUP_TLBRENTRY_OFFSET 80
#define LABOOT_SETUP_CRMD_VALUE_OFFSET 88
#define LABOOT_SETUP_POST_ENTRY_OFFSET 96
#define LABOOT_SETUP_BOOT_INFO_PTR_OFFSET 104
#define LABOOT_SETUP_RECLAIMABLE_CURSOR_OFFSET 112

#define LABOOT_BOOTINFO_BSP_OFFSET 0
#define LABOOT_BOOTINFO_DTB_PHYS_OFFSET 8
#define LABOOT_BOOTINFO_DTB_VIRT_OFFSET 16
#define LABOOT_BOOTINFO_HHDM_BASE_OFFSET 24
#define LABOOT_BOOTINFO_KERNEL_PHYS_BASE_OFFSET 32
#define LABOOT_BOOTINFO_KERNEL_VIRT_BASE_OFFSET 40
#define LABOOT_BOOTINFO_KERNEL_PHYS_END_OFFSET 48
#define LABOOT_BOOTINFO_KERNEL_VIRT_END_OFFSET 56
#define LABOOT_BOOTINFO_ROOT_PGTBL_PHYS_OFFSET 64
#define LABOOT_BOOTINFO_ROOT_PGTBL_VIRT_OFFSET 72
#define LABOOT_BOOTINFO_CMDLINE_PHYS_OFFSET 80
#define LABOOT_BOOTINFO_SYSTEM_TABLE_PHYS_OFFSET 88
#define LABOOT_BOOTINFO_CMDLINE_VIRT_OFFSET 96
#define LABOOT_BOOTINFO_SYSTEM_TABLE_VIRT_OFFSET 104
