#!/usr/bin/env python3
import json
import sys
from pathlib import Path


def default_config_path():
    local_config = Path("config.json")
    if local_config.exists():
        return local_config
    return Path("script/config.default.json")


def make_value(value):
    return str(value).replace("$", "$$").replace("#", "\\#")


def require_object(value, name):
    if not isinstance(value, dict):
        raise ValueError(f"{name} must be an object")
    return value


def require_string(value, name):
    if not isinstance(value, str) or not value:
        raise ValueError(f"{name} must be a non-empty string")
    return value


def optional_list(value, name):
    if value is None:
        return []
    if not isinstance(value, list):
        raise ValueError(f"{name} must be an array")
    return value


def resolve_arch_config(config, override_arch=None):
    config = require_object(config, "config")
    arch = override_arch or require_string(config.get("arch"), "arch")
    arch_config = require_object(config.get(arch), arch)
    return arch, arch_config


def emit_config(config, override_arch=None):
    config = require_object(config, "config")
    arch, arch_config = resolve_arch_config(config, override_arch)
    lines = [
        "# Generated by tools/config_gen/config_gen.py.",
        "# Do not edit this file directly.",
        "",
    ]

    mode = config.get("mode")
    if mode is not None:
        lines.append(f"build-mode ?= {make_value(mode)}")
    lines.append(f"architecture ?= {make_value(arch)}")

    qemu = arch_config.get("qemu")
    if qemu is not None:
        qemu = require_object(qemu, f"{arch}.qemu")
        memory = qemu.get("memory")
        if memory is not None:
            memory = require_object(memory, f"{arch}.qemu.memory")
            size = memory.get("size")
            maxmem = memory.get("maxmem")
            if size is not None and maxmem is not None:
                lines.append(
                    "qemu-memory-args ?= "
                    f"-m size={make_value(size)},maxmem={make_value(maxmem)}"
                )
            elif size is not None or maxmem is not None:
                raise ValueError(
                    f"{arch}.qemu.memory requires both size and maxmem"
                )

        attached = optional_list(qemu.get("attached"), f"{arch}.qemu.attached")
        if attached:
            lines.append(
                "qemu-attached-args ?= "
                + " ".join(make_value(item) for item in attached)
            )

    features = optional_list(arch_config.get("features"), f"{arch}.features")
    if features:
        lines.append("features ?= " + " ".join(make_value(item) for item in features))

    lines.append("")
    return "\n".join(lines)


def write_text_if_changed(path, content):
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def main(argv):
    if len(argv) > 4:
        print("usage: config_gen.py [config.json] [config.mk] [arch]", file=sys.stderr)
        return 2

    input_path = Path(argv[1]) if len(argv) >= 2 else default_config_path()
    output_path = Path(argv[2]) if len(argv) >= 3 else Path("config.mk")
    override_arch = argv[3] if len(argv) >= 4 else None

    try:
        with input_path.open(encoding="utf-8") as fp:
            config = json.load(fp)
        write_text_if_changed(output_path, emit_config(config, override_arch))
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"config_gen.py: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
