#!/usr/bin/env python3
"""Generate the global program registry from program metadata."""

from __future__ import annotations

from pathlib import Path

import build_headers
from libregistry import OwnerMeta, scan_programs


def emit(root: Path) -> str:
    programs = scan_programs(root)
    lines = [
        "# Generated by script/py/build_programs.py. Do not edit this file directly.",
        "",
        f"program-ids := {' '.join(program.id for program in programs)}",
        "",
    ]
    for program in programs:
        lines.extend(
            (
                f"program-{program.id}-makefile := {program.makefile}",
                f"program-{program.id}-target := {program.target}",
                "",
            )
        )
    return "\n".join(lines)


def emit_headers(root: Path) -> dict[str, str]:
    """Return module build headers keyed by their cache file names."""
    return {
        build_headers.module_name(program.id): build_headers.emit(
            program.id,
            program.root,
            f"$(path-obj)/module/{program.id}",
            f"$(path-bin)/{program.output}",
        )
        for program in scan_programs(root)
    }
