"""Emit per-component Make build headers."""

from __future__ import annotations


def library_name(owner_id: str) -> str:
    return f"build-header-lib-{owner_id}.mk"


def module_name(owner_id: str) -> str:
    return f"build-header-module-{owner_id}.mk"


def emit(owner_id: str, owner_root: str, obj_root: str, target: str) -> str:
    return "\n".join(
        (
            "# Generated by script/py/configure.py. Do not edit this file directly.",
            "",
            f"owner-id := {owner_id}",
            f"owner-root := {owner_root}",
            f"obj-root ?= {obj_root}",
            f"target ?= {target}",
            "",
        )
    )
