#!/usr/bin/env python3
"""Generate the global library registry and build targets from metadata.toml."""

from __future__ import annotations

from pathlib import Path

from libregistry import KNOWN_ARCHITECTURES, scan_libraries


def emit(root: Path) -> str:
    libraries = scan_libraries(root)
    libraries_by_arch = {
        arch: [
            library
            for library in libraries
            if not library.support_archs or arch in library.support_archs
        ]
        for arch in KNOWN_ARCHITECTURES
    }

    lines = [
        "# Generated by script/py/build_libs.py. Do not edit this file directly.",
        "",
    ]

    phony_targets = " ".join(f"build-lib-{library.id}" for library in libraries)
    if libraries:
        lines.append(f"library-ids := {' '.join(library.id for library in libraries)}")
        lines.append("")
        for library in libraries:
            lines.append(f"library-{library.id}-version := {library.version}")
            lines.append(f"library-{library.id}-makefile := {library.makefile}")
            lines.append(f"library-{library.id}-target := {library.target}")
            lines.append(f"library-{library.id}-include-c := {library.include_c}")
            lines.append(f"library-{library.id}-include-cpp := {library.include_cpp}")
            lines.append(f"library-{library.id}-include-asm := {library.include_asm}")
            lines.append("")

        for arch, arch_libraries in libraries_by_arch.items():
            lines.append(f"library-ids-{arch} := {' '.join(library.id for library in arch_libraries)}")
        lines.append("")

        lines.append(f".PHONY: {phony_targets} build-libs")
        lines.append("")
        for library in libraries:
            lines.append(f"build-lib-{library.id}:")
            lines.append(
                "\t$(q)$(MAKE) -f {makefile} global-env=$(global-env) "
                "arch=$(arch) q=$(q) {target}".format(
                    makefile=library.makefile,
                    target=library.target,
                )
            )
            lines.append("")
        for arch, arch_libraries in libraries_by_arch.items():
            lines.append(
                f"build-lib-targets-{arch} := "
                + " ".join(f"build-lib-{library.id}" for library in arch_libraries)
            )
        lines.append("")
        lines.append(".SECONDEXPANSION:")
        lines.append("build-libs: $$(build-lib-targets-$(arch))")
        lines.append('\t$(q)$(echo) "All libraries built"')
    else:
        lines.append("library-ids :=")
        for arch in KNOWN_ARCHITECTURES:
            lines.append(f"library-ids-{arch} :=")
        lines.append("")
        lines.append(".PHONY: build-libs")
        for arch in KNOWN_ARCHITECTURES:
            lines.append(f"build-lib-targets-{arch} :=")
        lines.append(".SECONDEXPANSION:")
        lines.append("build-libs:")
        lines.append('\t$(q)$(echo) "All libraries built"')

    lines.append("")
    return "\n".join(lines)
