#!/usr/bin/env python3
"""Generate library registry and build-target Make fragments from metadata.toml."""

from __future__ import annotations

from pathlib import Path

import build_ctx
from libregistry import KNOWN_ARCHITECTURES, LibraryMeta, scan_libraries


def _scan(root: Path) -> tuple[list[LibraryMeta], dict[str, list[LibraryMeta]]]:
    libraries = scan_libraries(root)
    seen_ids: dict[str, str] = {}
    for library in libraries:
        if library.id in seen_ids:
            raise ValueError(
                f"duplicate library id {library.id!r}: {seen_ids[library.id]} and {library.metadata_path}"
            )
        seen_ids[library.id] = library.metadata_path
    libraries_by_arch = {
        arch: [
            library
            for library in libraries
            if library.supports("freestanding", arch)
        ]
        for arch in KNOWN_ARCHITECTURES
    }
    return libraries, libraries_by_arch


def _header() -> list[str]:
    return [
        "# Generated by script/py/build_libs.py. Do not edit this file directly.",
        "",
    ]


def _emit_registry(
    libraries: list[LibraryMeta],
    libraries_by_arch: dict[str, list[LibraryMeta]],
) -> str:
    lines = _header()

    if libraries:
        lines.append(f"library-ids-all := {' '.join(library.id for library in libraries)}")
        lines.append("")
        for library in libraries:
            lines.append(f"library-{library.id}-version := {library.version}")
            lines.append(f"library-{library.id}-kind := {library.kind}")
            lines.append(f"library-{library.id}-libname := {library.libname}")
            lines.append(f"library-{library.id}-makefile := {library.makefile}")
            lines.append(f"library-{library.id}-target := {library.target}")
            lines.append(
                f"library-{library.id}-support-environments-all := {' '.join(library.support_environments)}"
            )
            for environment in library.support_environments:
                lines.append(
                    f"library-{library.id}-support-environments-$(is-{environment}) += {environment}"
                )
            lines.append(
                f"library-{library.id}-support-environments := $(strip $(library-{library.id}-support-environments-y))"
            )
            lines.append(
                f"library-{library.id}-support-archs := {' '.join(library.support_archs)}"
            )
            lines.append(f"library-{library.id}-archive := {library.archive_path}")
            lines.append(
                f"library-{library.id}-is-header-only := {'y' if library.is_header_only else 'n'}"
            )
            lines.append(f"library-{library.id}-include-c := {library.include_c}")
            lines.append(f"library-{library.id}-include-cpp := {library.include_cpp}")
            lines.append(f"library-{library.id}-include-asm := {library.include_asm}")
            for arch in KNOWN_ARCHITECTURES:
                lines.append(
                    f"library-{library.id}-ldscript-$(is-{arch}) := {library.arch_ldscripts.get(arch, '')}"
                )
                lines.append(f"library-{library.id}-crt0-$(is-{arch}) := {library.arch_crt0.get(arch, '')}")
                lines.append(f"library-{library.id}-crti-$(is-{arch}) := {library.arch_crti.get(arch, '')}")
                lines.append(f"library-{library.id}-crtn-$(is-{arch}) := {library.arch_crtn.get(arch, '')}")
            for field in ("ldscript", "crt0", "crti", "crtn"):
                lines.append(
                    f"library-{library.id}-{field} := $(library-{library.id}-{field}-y)"
                )
            if library.supports("host"):
                lines.append(
                    f"library-{library.id}-is-supported-$(is-host) := y"
                )
            for arch in KNOWN_ARCHITECTURES:
                if library.supports("freestanding", arch):
                    lines.append(
                        f"library-{library.id}-is-supported-$(is-freestanding-{arch}) := y"
                    )
            lines.append(
                f"library-{library.id}-is-supported := $(library-{library.id}-is-supported-y)"
            )
            lines.append("")
    else:
        lines.append("library-ids-all :=")

    for arch, arch_libraries in libraries_by_arch.items():
        lines.append(
            f"library-ids-$(is-freestanding-{arch}) += {' '.join(library.id for library in arch_libraries)}"
        )
    host_libraries = [library for library in libraries if library.supports("host")]
    lines.append(
        f"library-ids-$(is-host) += {' '.join(library.id for library in host_libraries)}"
    )
    lines.append("library-ids := $(strip $(library-ids-y))")
    lines.append("")
    return "\n".join(lines)


def _emit_build_targets(
    libraries: list[LibraryMeta],
    libraries_by_arch: dict[str, list[LibraryMeta]],
) -> str:
    lines = _header()
    phony_targets = " ".join(f"build-lib-{library.id}" for library in libraries)

    if phony_targets:
        lines.append(f".PHONY: {phony_targets} build-libs")
    else:
        lines.append(".PHONY: build-libs")
    lines.append("")

    for library in libraries:
        lines.append(f".PHONY: build-lib-{library.id}")
        lines.append(f"build-lib-{library.id}:")
        if not library.is_header_only:
            lines.append(
                "\t$(q)$(MAKE) -f {makefile} global-env=$(global-env) "
                "arch=$(arch) q=$(q) ctx=$(path-ctx)/{ctx} {target}".format(
                    makefile=library.makefile,
                    ctx=build_ctx.library_name(library.id),
                    target=library.target,
                )
            )
        lines.append("")

    for arch, arch_libraries in libraries_by_arch.items():
        lines.append(
            f"build-lib-targets-$(is-freestanding-{arch}) += "
            + " ".join(
                f"build-lib-{library.id}"
                for library in arch_libraries
                if not library.is_header_only
            )
        )
    lines.append("")
    lines.append(".SECONDEXPANSION:")
    lines.append("build-lib-targets := $(strip $(build-lib-targets-y))")
    lines.append("build-libs: $$(build-lib-targets)")
    lines.append('\t$(q)$(echo) "All libraries built"')

    host_libraries = [library for library in libraries if library.supports("host")]
    host_archive_libraries = [
        library for library in host_libraries if not library.is_header_only
    ]
    lines.append("")
    lines.append(
        ".PHONY: "
        + " ".join(f"host-build-lib-{library.id}" for library in host_libraries)
    )
    for library in host_libraries:
        lines.append(f"host-build-lib-{library.id}:")
        if library.is_header_only:
            lines.append(
                "\t$(q)$(MAKE) --no-print-directory _host-header-check "
                f"lib={library.id} mode=$(mode) sanitize=$(sanitize)"
            )
        else:
            lines.append(
                "\t$(q)$(MAKE) -f {makefile} global-env=$(global-env) "
                "environment=host allow-target-arch=$(allow-target-arch) mode=$(mode) sanitize=$(sanitize) q=$(q) "
                "ctx=$(path-ctx)/{ctx} "
                "deps-file=$(path-deps)/host-{owner}.mk {target}".format(
                    makefile=library.makefile,
                    ctx=build_ctx.library_name(library.id),
                    owner=library.id,
                    target=library.target,
                )
            )
        lines.append("")
    lines.append(
        "host-build-lib-targets-$(is-host) += "
        + " ".join(
            f"host-build-lib-{library.id}" for library in host_archive_libraries
        )
    )
    lines.append("host-build-lib-targets := $(strip $(host-build-lib-targets-y))")
    lines.append(".PHONY: _build-host-libs")
    lines.append("_build-host-libs: $(host-build-lib-targets)")
    lines.append('\t$(q)$(echo) "All host libraries built"')

    lines.append("")
    return "\n".join(lines)


def emit(root: Path) -> tuple[str, str]:
    """Return the global registry and build-target fragments in that order."""
    libraries, libraries_by_arch = _scan(root)
    return (
        _emit_registry(libraries, libraries_by_arch),
        _emit_build_targets(libraries, libraries_by_arch),
    )


def emit_ctx(root: Path) -> dict[str, str]:
    """Return library build contexts keyed by their cache file names."""
    libraries, _ = _scan(root)
    return {
        build_ctx.library_name(library.id): build_ctx.emit(
            library.id,
            library.root,
            f"$(path-obj)/libs/{library.id}",
            library.archive_path,
        )
        for library in libraries
    }
