#!/usr/bin/env python3
"""Generate library registry and build-target Make fragments from metadata.toml."""

from __future__ import annotations

from pathlib import Path

import build_headers
from libregistry import KNOWN_ARCHITECTURES, LibraryMeta, scan_libraries


def _scan(root: Path) -> tuple[list[LibraryMeta], dict[str, list[LibraryMeta]]]:
    libraries = scan_libraries(root)
    seen_ids: dict[str, str] = {}
    for library in libraries:
        if library.id in seen_ids:
            raise ValueError(
                f"duplicate library id {library.id!r}: {seen_ids[library.id]} and {library.metadata_path}"
            )
        seen_ids[library.id] = library.metadata_path
    libraries_by_arch = {
        arch: [
            library
            for library in libraries
            if not library.support_archs or arch in library.support_archs
        ]
        for arch in KNOWN_ARCHITECTURES
    }
    return libraries, libraries_by_arch


def _header() -> list[str]:
    return [
        "# Generated by script/py/build_libs.py. Do not edit this file directly.",
        "",
    ]


def _emit_registry(
    libraries: list[LibraryMeta],
    libraries_by_arch: dict[str, list[LibraryMeta]],
) -> str:
    lines = _header()

    if libraries:
        lines.append(f"library-ids := {' '.join(library.id for library in libraries)}")
        lines.append("")
        for library in libraries:
            lines.append(f"library-{library.id}-version := {library.version}")
            lines.append(f"library-{library.id}-kind := {library.kind}")
            lines.append(f"library-{library.id}-libname := {library.libname}")
            lines.append(f"library-{library.id}-makefile := {library.makefile}")
            lines.append(f"library-{library.id}-target := {library.target}")
            lines.append(f"library-{library.id}-archive := {library.archive_path}")
            lines.append(
                f"library-{library.id}-is-header-only := {'y' if library.is_header_only else 'n'}"
            )
            lines.append(f"library-{library.id}-include-c := {library.include_c}")
            lines.append(f"library-{library.id}-include-cpp := {library.include_cpp}")
            lines.append(f"library-{library.id}-include-asm := {library.include_asm}")
            for arch in KNOWN_ARCHITECTURES:
                lines.append(
                    f"library-{library.id}-ldscript-{arch} := {library.arch_ldscripts.get(arch, '')}"
                )
                lines.append(f"library-{library.id}-crt0-{arch} := {library.arch_crt0.get(arch, '')}")
                lines.append(f"library-{library.id}-crti-{arch} := {library.arch_crti.get(arch, '')}")
                lines.append(f"library-{library.id}-crtn-{arch} := {library.arch_crtn.get(arch, '')}")
            lines.append("")
    else:
        lines.append("library-ids :=")

    for arch, arch_libraries in libraries_by_arch.items():
        lines.append(f"library-ids-{arch} := {' '.join(library.id for library in arch_libraries)}")
    lines.append("")
    return "\n".join(lines)


def _emit_build_targets(
    libraries: list[LibraryMeta],
    libraries_by_arch: dict[str, list[LibraryMeta]],
) -> str:
    lines = _header()
    phony_targets = " ".join(f"build-lib-{library.id}" for library in libraries)

    if phony_targets:
        lines.append(f".PHONY: {phony_targets} build-libs")
    else:
        lines.append(".PHONY: build-libs")
    lines.append("")

    for library in libraries:
        lines.append(f".PHONY: build-lib-{library.id}")
        lines.append(f"build-lib-{library.id}:")
        if not library.is_header_only:
            lines.append(
                "\t$(q)$(MAKE) -f {makefile} global-env=$(global-env) "
                "arch=$(arch) q=$(q) build-header=$(path-cache)/{header} {target}".format(
                    makefile=library.makefile,
                    header=build_headers.library_name(library.id),
                    target=library.target,
                )
            )
        lines.append("")

    for arch, arch_libraries in libraries_by_arch.items():
        lines.append(
            f"build-lib-targets-{arch} := "
            + " ".join(
                f"build-lib-{library.id}"
                for library in arch_libraries
                if not library.is_header_only
            )
        )
    lines.append("")
    lines.append(".SECONDEXPANSION:")
    lines.append("build-libs: $$(build-lib-targets-$(arch))")
    lines.append('\t$(q)$(echo) "All libraries built"')

    lines.append("")
    return "\n".join(lines)


def emit(root: Path) -> tuple[str, str]:
    """Return the global registry and build-target fragments in that order."""
    libraries, libraries_by_arch = _scan(root)
    return (
        _emit_registry(libraries, libraries_by_arch),
        _emit_build_targets(libraries, libraries_by_arch),
    )


def emit_headers(root: Path) -> dict[str, str]:
    """Return component build headers keyed by their cache file names."""
    libraries, _ = _scan(root)
    return {
        build_headers.library_name(library.id): build_headers.emit(
            library.id,
            library.root,
            f"$(path-obj)/libs/{library.id}",
            library.archive_path,
        )
        for library in libraries
    }
