#!/usr/bin/env python3
"""Generate Make configuration files from a selected TOML configuration set."""

from __future__ import annotations

import importlib.util
import os
import sys
import tempfile
from pathlib import Path

import tomllib

import build_libs
import resolve_deps


ROOT = Path(__file__).resolve().parents[2]
CONFIG_ROOT = ROOT / "config"
CACHE_ROOT = ROOT / "script" / ".cache"


def parse_arguments(arguments: list[str]) -> tuple[str, str]:
    values = {}
    for argument in arguments:
        key, separator, value = argument.partition("=")
        if not separator or key not in {"config", "arch"} or not value:
            raise ValueError(f"invalid argument: {argument}")
        if key in values:
            raise ValueError(f"duplicate argument: {key}")
        values[key] = value
    return values.get("config", "default"), values.get("arch", "riscv64")


def load_emitter(name: str):
    path = Path(__file__).resolve().parent / f"{name}.py"
    if not path.is_file():
        raise ValueError(f"no emitter for {name}.toml")

    spec = importlib.util.spec_from_file_location(f"config_emitter_{name}", path)
    if spec is None or spec.loader is None:
        raise ValueError(f"cannot load emitter for {name}.toml")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    sys.path.insert(0, str(path.parent))
    try:
        spec.loader.exec_module(module)
    finally:
        sys.path.pop(0)
    return module


def write_text_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent, text=True
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as temporary_file:
            temporary_file.write(content)
            temporary_file.flush()
            os.fsync(temporary_file.fileno())
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def generate(config_name: str, arch: str) -> None:
    config_dir = (CONFIG_ROOT / config_name).resolve()
    if CONFIG_ROOT not in config_dir.parents or not config_dir.is_dir():
        raise ValueError(f"configuration directory does not exist: {config_name}")

    toml_files = sorted(config_dir.glob("*.toml"))
    if not toml_files:
        raise ValueError(f"configuration directory is empty: {config_dir}")

    generated = []
    for toml_path in toml_files:
        with toml_path.open("rb") as config_file:
            data = tomllib.load(config_file)
        emitter = load_emitter(toml_path.stem)
        generated_name = f"{toml_path.stem}.mk"
        write_text_if_changed(
            CACHE_ROOT / generated_name,
            emitter.emit(data),
        )
        generated.append(generated_name)

    libraries_name = "libraries.mk"
    write_text_if_changed(
        CACHE_ROOT / libraries_name,
        build_libs.emit(ROOT),
    )
    generated.append(libraries_name)

    deps_kernel_name = "deps-kernel.mk"
    write_text_if_changed(
        CACHE_ROOT / deps_kernel_name,
        resolve_deps.emit(ROOT, "kernel", ROOT / "kernel", arch),
    )
    generated.append(deps_kernel_name)

    include_lines = [
        "# Generated by script/py/configure.py. Do not edit this file directly.",
        "",
    ]
    include_lines.extend(
        f"-include $(path-cache)/{name}"
        for name in generated
        if name in {"clang.mk", "kernel.mk", "path.mk", "qemu.mk"}
    )
    include_lines.append("")
    write_text_if_changed(CACHE_ROOT / "config.mk", "\n".join(include_lines))


def main(arguments: list[str]) -> int:
    try:
        config_name, arch = parse_arguments(arguments)
        generate(config_name, arch)
    except (OSError, tomllib.TOMLDecodeError, TypeError, ValueError) as error:
        print(f"configure.py: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
