#!/usr/bin/env python3
"""Common TOML-to-Make emission helpers."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable


def _flatten_path(path: str) -> list[str]:
    return [part for part in path.split(".") if part]


def _make_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, list):
        return " ".join(_make_value(item) for item in value)
    if isinstance(value, (str, int, float)):
        return str(value).replace("#", r"\#")
    raise TypeError(f"unsupported TOML value: {type(value).__name__}")


def _make_collection_value(value: str) -> str:
    return value.replace("#", r"\#")


def _lookup(data: Any, path: list[str], captures: dict[str, str]) -> list[tuple[Any, dict[str, str]]]:
    if not path:
        return [(data, captures)]
    if not isinstance(data, dict):
        return []

    head, *tail = path
    if head.startswith("$"):
        results = []
        capture_name = head[1:]
        for key, value in data.items():
            next_captures = dict(captures)
            next_captures[capture_name] = key
            results.extend(_lookup(value, tail, next_captures))
        return results

    if head not in data:
        return []
    return _lookup(data[head], tail, captures)


def _expand(value: str, captures: dict[str, str]) -> str:
    for name, replacement in captures.items():
        value = value.replace(f"${name}", replacement)
    return value


@dataclass(frozen=True)
class ValueEmitter:
    """A target-aware value transformer for keymap."""

    target: str
    transform: Callable[[Any], Any]

    def __call__(self, value: Any, captures: dict[str, str]) -> tuple[str, Any]:
        return _expand(self.target, captures), self.transform(value)


def emit(target: str, transform: Callable[[Any], Any] = lambda value: value) -> ValueEmitter:
    return ValueEmitter(target, transform)


class MkEmitter:
    def __init__(self, data: dict[str, Any]):
        self.data = data
        self._lines: list[str] = []
        self._collections: dict[str, tuple[dict[str, str], list[str]]] = {}

    def keymap(self, key: str, newkey: str | ValueEmitter) -> None:
        for value, captures in _lookup(self.data, _flatten_path(key), {}):
            if isinstance(newkey, str):
                target = _expand(newkey, captures)
                rendered = value
            else:
                target, rendered = newkey(value, captures)
            self._lines.append(f"{target} := {_make_value(rendered)}")

    def collect(
        self,
        key: str,
        collector: Callable[[Any, dict[str, str]], list[str]],
        collection_id: str,
    ) -> None:
        for value, captures in _lookup(self.data, _flatten_path(key), {}):
            values = value if isinstance(value, list) else [value]
            for index, item in enumerate(values):
                item_captures = dict(captures)
                item_captures["index"] = str(index)
                resolved_id = _expand(collection_id, item_captures)
                fragments = collector(item, item_captures)
                if not isinstance(fragments, list):
                    raise TypeError("collector must return a list of strings")
                if not all(isinstance(fragment, str) for fragment in fragments):
                    raise TypeError("collector fragments must be strings")
                if resolved_id not in self._collections:
                    self._collections[resolved_id] = (item_captures, [])
                self._collections[resolved_id][1].extend(fragments)

    def emit_collection(self, collection_id: str, collection_key: str) -> None:
        for resolved_id, (captures, fragments) in self._collections.items():
            if _expand(collection_id, captures) != resolved_id:
                continue
            target = _expand(collection_key, captures)
            if not fragments:
                self._lines.append(f"{target} :=")
                continue
            self._lines.append(f"{target} := \\")
            self._lines.extend(
                f"\t{_make_collection_value(fragment)} \\"
                for fragment in fragments[:-1]
            )
            self._lines.append(f"\t{_make_collection_value(fragments[-1])}")

    def render(self, source_name: str) -> str:
        lines = [
            f"# Generated from {source_name}. Do not edit this file directly.",
            "",
        ]
        lines.extend(self._lines)
        lines.append("")
        return "\n".join(lines)
