#!/usr/bin/env python3
"""Resolve target dependencies against the generated library registry."""

from __future__ import annotations

from pathlib import Path
import tomllib

from libregistry import LibraryMeta, libraries_for_arch
import semver


def _select_library(
    library_index: dict[str, list[LibraryMeta]],
    dep_name: str,
    dep_version: str,
    target_path: Path,
) -> LibraryMeta:
    candidates = library_index.get(dep_name, [])
    if not candidates:
        raise ValueError(
            f"{target_path}: dependency {dep_name!r} is not registered for the current architecture"
        )

    matching = [candidate for candidate in candidates if semver.matches(candidate.version, dep_version)]
    if not matching:
        raise ValueError(
            f"{target_path}: dependency {dep_name!r} version expression {dep_version!r} matched no libraries"
        )
    if len(matching) != 1:
        raise ValueError(
            f"{target_path}: dependency {dep_name!r} version expression {dep_version!r} matched multiple libraries"
        )
    return matching[0]


def _parse_dep_entries(entries: object, target_path: Path) -> list[tuple[str, str]]:
    if entries is None:
        return []
    if not isinstance(entries, list):
        raise ValueError(f"{target_path}: dependencies must be an array of tables")
    result = []
    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError(f"{target_path}: dependency entries must be tables")
        dep_name = entry.get("lib")
        dep_version = entry.get("version")
        if not isinstance(dep_name, str) or not dep_name:
            raise ValueError(f"{target_path}: dependency lib must be a non-empty string")
        if not isinstance(dep_version, str) or not dep_version:
            raise ValueError(f"{target_path}: dependency version must be a non-empty string")
        result.append((dep_name, dep_version))
    return result


def emit(root: Path, target_name: str, target_root: Path, current_arch: str) -> str:
    target_path = target_root / "dependencies.toml"
    if not target_path.is_file():
        raise ValueError(f"{target_path} does not exist")

    with target_path.open("rb") as dependency_file:
        data = tomllib.load(dependency_file)

    common_deps = _parse_dep_entries(data.get("dependencies"), target_path)
    arch_entries = {
        key: _parse_dep_entries(value.get("dependencies"), target_path)
        for key, value in data.items()
        if isinstance(value, dict) and key != "dependencies"
    }

    current_library_index: dict[str, list[LibraryMeta]] = {}
    for library in libraries_for_arch(root, current_arch):
        current_library_index.setdefault(library.id, []).append(library)

    default_resolved = [
        _select_library(current_library_index, dep_name, dep_version, target_path)
        for dep_name, dep_version in common_deps
    ]

    common_resolved: dict[str, list[LibraryMeta]] = {}
    for arch in sorted(arch_entries):
        arch_library_index: dict[str, list[LibraryMeta]] = {}
        for library in libraries_for_arch(root, arch):
            arch_library_index.setdefault(library.id, []).append(library)
        common_resolved[arch] = [
            _select_library(arch_library_index, dep_name, dep_version, target_path)
            for dep_name, dep_version in common_deps
        ]

    lines = [
        f"# Generated by script/py/resolve_deps.py for {target_name}. Do not edit this file directly.",
        "",
        f"{target_name}-libraries := {' '.join(library.id for library in default_resolved)}",
        f"{target_name}-includes-c := {' '.join(filter(None, (library.include_c for library in default_resolved)))}",
        f"{target_name}-includes-cpp := {' '.join(filter(None, (library.include_cpp for library in default_resolved)))}",
        f"{target_name}-includes-asm := {' '.join(filter(None, (library.include_asm for library in default_resolved)))}",
        "",
    ]

    for arch, deps in sorted(arch_entries.items()):
        arch_library_index: dict[str, list[LibraryMeta]] = {}
        for library in libraries_for_arch(root, arch):
            arch_library_index.setdefault(library.id, []).append(library)
        resolved_arch = common_resolved[arch] + [
            _select_library(arch_library_index, dep_name, dep_version, target_path)
            for dep_name, dep_version in deps
        ]
        lines.append(f"{target_name}-libraries-{arch} := {' '.join(library.id for library in resolved_arch)}")
        lines.append(f"{target_name}-includes-c-{arch} := {' '.join(filter(None, (library.include_c for library in resolved_arch)))}")
        lines.append(f"{target_name}-includes-cpp-{arch} := {' '.join(filter(None, (library.include_cpp for library in resolved_arch)))}")
        lines.append(f"{target_name}-includes-asm-{arch} := {' '.join(filter(None, (library.include_asm for library in resolved_arch)))}")
        lines.append("")

    return "\n".join(lines)
