#!/usr/bin/env python3
"""Persist the selected build architecture and mode."""

import os
import sys
import tempfile
from pathlib import Path


SUPPORTED_ARCHITECTURES = {"riscv64", "loongarch64"}
SUPPORTED_MODES = {"debug", "release"}


def parse_arguments(arguments):
    values = {}
    for argument in arguments:
        key, separator, value = argument.partition("=")
        if not separator or key not in {"arch", "mode"} or not value:
            raise ValueError(f"invalid argument: {argument}")
        if key in values:
            raise ValueError(f"duplicate argument: {key}")
        values[key] = value

    missing = {"arch", "mode"} - values.keys()
    if missing:
        raise ValueError("missing argument: " + ", ".join(sorted(missing)))

    if values["arch"] not in SUPPORTED_ARCHITECTURES:
        raise ValueError(f"unsupported architecture: {values['arch']}")
    if values["mode"] not in SUPPORTED_MODES:
        raise ValueError(f"unsupported mode: {values['mode']}")
    return values


def write_switch_file(path, values):
    path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "# Generated by script/py/switch.py. Do not edit this file directly.\n"
        f"cached-arch := {values['arch']}\n"
        f"cached-mode := {values['mode']}\n"
    )

    fd, temporary_name = tempfile.mkstemp(
        prefix=".switch.mk.", dir=path.parent, text=True
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as temporary_file:
            temporary_file.write(content)
            temporary_file.flush()
            os.fsync(temporary_file.fileno())
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def main(arguments):
    try:
        values = parse_arguments(arguments)
        cache_path = Path(__file__).resolve().parent.parent / ".cache" / ".switch.mk"
        write_switch_file(cache_path, values)
    except (OSError, ValueError) as error:
        print(f"switch.py: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
